### ISSUE TITLE
Add syntax highlighting to code in Fusion

### ISSUE THREAD

**Issue by arthtyagi** [The-Domecode/domecode-opensource#4]

**Comment by charlygg** [comment]
Hello, Could I try this issue? I could take some time learning because my strength area are Databases (Oracle and SQL Server) but I am interesting in learning and develop Frontent Technologies

Let me know if I understood, in the Fusion page (really nice app), it is required to color syntax code (html, css and javascript)

**Comment by arthtyagi** [comment]
yes exactly, you got it.

**Comment by arthtyagi** [comment]
come join our discord server btw https://discord.gg/ZwTJPNB
